#! /usr/bin/env node

const {resolve} = require('path');
const Jasmine = require('jasmine');
const jasmine = new Jasmine();

jasmine.loadConfigFile(resolve(__dirname, 'jasmine.json'));
jasmine.execute();